services:
  postgres:
    image: postgres:17.2-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=screener
      - POSTGRES_USER=screener
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: